# travis-ci.org build & test configuration
language: python
python:
    - "2.7"
    - "3.4"
env:
    - ROOT=v5-34-18
    - ROOT=master
install: source ci/install.sh
script: bash ci/test.sh
after_success:
    - time coveralls
cache: apt
